spring.datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    maxEvictableIdleTimeMillis: 40000
    validationQuety: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    defaultAutoCommit: true
    filters: stat


